# Databricks notebook source
# DBTITLE 1,Install dependencies
# MAGIC %pip install dbldatagen --quiet
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# DBTITLE 1,Import dbldatagen
import dbldatagen as dg

# COMMAND ----------

# DBTITLE 1,Create Schema and Tables
CATALOG = "aw_serverless_stable_catalog"
SCHEMA = "aibi_member_claims"

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")

statements = []
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.dim_member_v1 (member_sk BIGINT, mbr_source_member_id STRING, mbr_member_id INT, mbr_deers_beneficiary_id STRING, mbr_deers_family_id STRING, mbr_sponsor_ssn STRING, mbr_current_pcp_eff_date DATE, mbr_current_pcp_nbr STRING, mbr_dob DATE, mbr_race STRING, mbr_sex STRING, mbr_ethnicity STRING, mbr_first_name STRING, mbr_middle_name STRING, mbr_last_name STRING, mbr_full_name STRING, mbr_marital_status STRING, mbr_deceased_date DATE, mbr_email STRING, mbr_phone_nbr STRING, mbr_mobile_nbr STRING, mbr_work_nbr STRING, mbr_sub_group_cd STRING, mbr_idcard_issue_date DATE, mbr_line_of_business STRING, mbr_text_opt_in STRING, mbr_current_riders STRING, mbr_authorized_rep STRING, mbr_alt_sub_nbr STRING, mbr_relationship_type STRING, mbr_salary_tier STRING, mbr_pcp_auto_assigned STRING, mbr_secured_flag STRING, mbr_pharmacy_discount_flag STRING, mbr_employee_id STRING, mbr_line_of_business_name STRING, mbr_responsible_party_id STRING, mbr_responsible_party_name STRING, mbr_deceased_flag STRING, mbr_pcp_lock_in_indicator STRING, mbr_alt_person_nbr STRING, mbr_state STRING, mbr_zip_code STRING, mbr_pcp_lock_in_type STRING, mbr_provider_group_name STRING, mbr_name_suffix STRING, mbr_sub_flag INT, mbr_sub_ssn STRING, mbr_extract_date DATE, mbr_medicaid_case_nbr STRING, mbr_relationship_ind STRING, source_system_code STRING, source_system_name STRING, record_hash STRING, created_at TIMESTAMP, updated_at TIMESTAMP, is_active BOOLEAN, end_date TIMESTAMP) USING DELTA COMMENT 'Member dimension'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.dim_address_v1 (address_key BIGINT, entity_type_key STRING, entity_dimension_key BIGINT, address_type_code STRING, street_address_1 STRING, street_address_2 STRING, city STRING, state STRING, zip_code STRING, country_code STRING, county STRING, is_active BOOLEAN, valid_from_date TIMESTAMP, valid_to_date TIMESTAMP, source_system_code STRING, source_system_name STRING, record_hash STRING, created_at TIMESTAMP, updated_at TIMESTAMP) USING DELTA COMMENT 'Address dimension'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.dim_provider_v1 (provider_sk BIGINT, assigned_provider_sk BIGINT, source_provider_id STRING, provider_npi STRING, provider_tax_id STRING, provider_name STRING, provider_address_sk BIGINT, pcp_flag BOOLEAN, affiliation_id STRING, valid_from_date TIMESTAMP, valid_to_date TIMESTAMP, is_active BOOLEAN, source_system STRING, created_at TIMESTAMP, updated_at TIMESTAMP, last_update_dt TIMESTAMP, record_hash STRING) USING DELTA COMMENT 'Provider dimension'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.dim_member_identifier_v1 (mbr_identifier_sk BIGINT, member_sk BIGINT, id_type STRING, id_value STRING, source_system_code STRING, source_system_name STRING, valid_to_date TIMESTAMP, valid_from_date TIMESTAMP, is_active BOOLEAN, created_at TIMESTAMP, updated_at TIMESTAMP, record_hash STRING) USING DELTA COMMENT 'Member identifier bridge'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.dim_member_history_v1 (mbr_history_sk BIGINT, member_sk BIGINT, mbr_source_member_id STRING, mbr_member_id INT, mbr_dob DATE, mbr_race STRING, mbr_sex STRING, mbr_ethnicity STRING, mbr_first_name STRING, mbr_last_name STRING, mbr_full_name STRING, mbr_marital_status STRING, mbr_line_of_business STRING, mbr_state STRING, mbr_zip_code STRING, source_system_code STRING, source_system_name STRING, record_hash STRING, created_at TIMESTAMP, updated_at TIMESTAMP, is_active BOOLEAN, valid_to_date TIMESTAMP, valid_from_date TIMESTAMP) USING DELTA COMMENT 'Member history snapshot'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.fact_member_enrollment_v1 (source_system STRING, src_member_business_id INT, mbr_enr_source_member_id VARCHAR(30), mbr_enr_insured_id STRING, mbr_enr_contract_id STRING, mbr_enr_insured_code VARCHAR(2), mbr_enr_insured_add_date TIMESTAMP, mbr_enr_insured_event_date TIMESTAMP, mbr_enr_insured_event_id STRING, mbr_enr_insured_event_code VARCHAR(2), mbr_enr_status STRING, mbr_enr_insured_event_add_date TIMESTAMP, mbr_enr_plan_id STRING, mbr_enr_line_of_business STRING, mbr_enr_line_of_business_id VARCHAR(8), mbr_enr_group_name VARCHAR(50), mbr_enr_subgroup_name VARCHAR(50), mbr_enr_effective_date DATE, mbr_enr_termination_date DATE, mbr_enr_termination_event_date DATE, mbr_enr_termination_reason STRING, mbr_enr_product_id STRING, mbr_enr_group_ck STRING, mbr_enr_group_code STRING, mbr_enr_subgroup_ck STRING, mbr_enr_subgroup_code STRING, is_active BOOLEAN, id_value STRING, id_type STRING, member_sk BIGINT, enrollment_sk STRING, payload_hash STRING) USING DELTA COMMENT 'Member enrollment fact'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.fact_claim_header_v1 (clm_header_sk BIGINT, clm_id INT, clm_claim_id STRING, clm_claim_type STRING, clm_bill_type STRING, clm_admit_date DATE, clm_claim_thru_date DATE, clm_discharge_date DATE, clm_admission_type STRING, clm_admission_source STRING, clm_member_nbr STRING, clm_member_name STRING, clm_member_sk BIGINT, clm_line_of_business STRING, clm_covered_days INT, clm_billing_provider STRING, clm_referring_provider STRING, clm_is_par_submitting_provider STRING, clm_is_par_referring_provider BOOLEAN, clm_is_par_rendering_provider BOOLEAN, clm_service_facility_address_sk BIGINT, clm_admitting_diagnosis_code STRING, clm_diagnosis_1 STRING, clm_diagnosis_1_icd_method STRING, clm_diagnosis_1_poa STRING, clm_drg_code STRING, clm_service_type_code STRING, clm_cob_type STRING, clm_claim_timely_filing STRING, clm_add_date DATE, clm_extract_date TIMESTAMP, is_active BOOLEAN, end_date TIMESTAMP, record_hash STRING, created_at TIMESTAMP, updated_at TIMESTAMP, source_system_code STRING, source_system_name STRING) USING DELTA COMMENT 'Claim header fact'""")
statements.append("""CREATE TABLE IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims.fact_claim_detail_v1 (clm_dtl_claim_id STRING, clm_dtl_line_nbr STRING, clm_dtl_original_source_claim_id STRING, clm_dtl_source_system STRING, clm_dtl_member_nbr_sk VARCHAR(30), clmdetail_admit_dt TIMESTAMP, clm_dtl_specific_dos_date DATE, clm_dtl_specific_dos_thru_date DATE, clm_dtl_ap_posting_date DATE, clm_dtl_claim_receive_date TIMESTAMP, clm_dtl_check_date TIMESTAMP, clm_dtl_last_update_date TIMESTAMP, clm_dtl_benefit_category STRING, clm_dtl_benefit_level STRING, clm_dtl_claim_type STRING, clm_dtl_allowed_amt DECIMAL(28,4), clm_dtl_billed_amt DECIMAL(27,4), clm_dtl_deduct_amt DECIMAL(27,4), clm_dtl_net_amt DECIMAL(28,4), clm_dtl_paid_amt DECIMAL(28,4), clm_dtl_actual_paid_amt DECIMAL(38,4), clm_dtl_not_covered_amt DECIMAL(27,4), clm_dtl_co_insurance_amt DECIMAL(27,4), clm_dtl_other_adjustments_amt DECIMAL(30,2), clm_dtl_cob_savings DECIMAL(32,4), clm_dtl_loic_paid_amt DECIMAL(19,4), clm_dtl_loic_allowed_amt DECIMAL(19,4), clm_dtl_interest_amt DECIMAL(38,6), clm_dtl_prompt_pay_discount_amt DECIMAL(20,4), clm_dtl_interest_discount_amt DECIMAL(38,6), clm_dtl_interest_discount_flag STRING, clm_dtl_copay_amt DECIMAL(27,4), clm_dtl_copay_reason VARCHAR(35), clm_dtl_st_cd VARCHAR(1), clm_dtl_reason_code_sk STRING, clm_dtl_line_status STRING, clm_dtl_clean_claim_ind STRING, clm_dtl_place_of_service VARCHAR(2), clm_dtl_fee_schedule_code VARCHAR(3), clm_dtl_adjudication_status STRING, clm_dtl_procedure_code VARCHAR(15), clm_dtl_procedure_modifier VARCHAR(2), clm_dtl_procedure_qty DECIMAL(15,3), clm_dtl_revenue_code VARCHAR(30), clm_dtl_paid_days DECIMAL(36,3), is_active BOOLEAN, updated_at TIMESTAMP, created_at TIMESTAMP) USING DELTA COMMENT 'Claim detail fact'""")

for stmt in statements:
    spark.sql(stmt)
print(f"Created or verified {len(statements)} Delta tables")

