"""LakebaseStore - Postgres-backed persistence for Agent Mode runs.

Uses Databricks Lakebase (managed Postgres) for real-time event storage.
This enables:
- Fast writes during agent execution (no SQL warehouse latency)
- Real-time reads for SSE streaming
- Run history with tool call detail
- Resume from failed step
- Multi-user concurrency

Schema mirrors the run_manifest.json format generated by the pipeline,
extended with a tool_events table for the detailed execution timeline.

Connection: Uses the Lakebase project configured in aibi.app.yml.
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Optional

import psycopg2
from psycopg2.extras import RealDictCursor, Json

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# DDL for Lakebase tables (run on first use)
# ---------------------------------------------------------------------------

SCHEMA_DDL = """
CREATE TABLE IF NOT EXISTS agent_runs (
    run_id          TEXT PRIMARY KEY,
    domain          TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    duration_s      REAL,
    total_steps     INT DEFAULT 4,
    steps_completed INT DEFAULT 0,
    current_step    TEXT,
    error           TEXT,
    run_manifest    JSONB,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agent_steps (
    id              SERIAL PRIMARY KEY,
    run_id          TEXT NOT NULL REFERENCES agent_runs(run_id),
    step_name       TEXT NOT NULL,
    step_index      INT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending',
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    duration_s      REAL,
    iterations      INT DEFAULT 0,
    tool_calls      INT DEFAULT 0,
    summary         TEXT,
    artifacts       JSONB DEFAULT '[]',
    error           TEXT
);

CREATE TABLE IF NOT EXISTS agent_events (
    id              SERIAL PRIMARY KEY,
    run_id          TEXT NOT NULL REFERENCES agent_runs(run_id),
    step_name       TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    payload         JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_events_run ON agent_events(run_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_steps_run ON agent_steps(run_id, step_index);
CREATE INDEX IF NOT EXISTS idx_agent_runs_domain ON agent_runs(domain, created_at DESC);
"""


class LakebaseStore:
    """Postgres-backed store for Agent Mode pipeline execution.

    Usage:
        store = LakebaseStore()
        store.create_run(run_id, domain)
        store.log_event(run_id, step, 'tool_call', {...})
        events = store.get_events_since(run_id, last_id)
    """

    def __init__(self, connection_string: Optional[str] = None):
        """Initialize with Lakebase Postgres connection.

        Args:
            connection_string: Postgres DSN. If None, reads from
                LAKEBASE_CONNECTION_STRING env var.
        """
        self._dsn = connection_string or os.environ.get('LAKEBASE_CONNECTION_STRING', '')
        self._conn = None
        self._initialized = False

    def _get_conn(self):
        """Get or create connection."""
        if self._conn is None or self._conn.closed:
            self._conn = psycopg2.connect(self._dsn)
            self._conn.autocommit = True
        if not self._initialized:
            self._ensure_schema()
            self._initialized = True
        return self._conn

    def _ensure_schema(self):
        """Create tables if they don't exist."""
        try:
            with self._get_conn().cursor() as cur:
                cur.execute(SCHEMA_DDL)
            logger.info("LakebaseStore: schema initialized")
        except Exception as e:
            logger.error(f"LakebaseStore: schema init failed: {e}")

    # ------------------------------------------------------------------
    # Run operations
    # ------------------------------------------------------------------

    def create_run(self, run_id: str, domain: str, total_steps: int = 4) -> None:
        """Create a new agent run."""
        with self._get_conn().cursor() as cur:
            cur.execute(
                "INSERT INTO agent_runs (run_id, domain, status, total_steps, started_at) "
                "VALUES (%s, %s, 'running', %s, NOW())",
                (run_id, domain, total_steps)
            )

    def update_run(self, run_id: str, status: str,
                   steps_completed: Optional[int] = None,
                   current_step: Optional[str] = None,
                   duration_s: Optional[float] = None,
                   error: Optional[str] = None,
                   run_manifest: Optional[dict] = None) -> None:
        """Update run status and metadata."""
        sets = ["status = %s", "updated_at = NOW()"]
        params = [status]

        if steps_completed is not None:
            sets.append("steps_completed = %s")
            params.append(steps_completed)
        if current_step is not None:
            sets.append("current_step = %s")
            params.append(current_step)
        if duration_s is not None:
            sets.append("duration_s = %s")
            params.append(duration_s)
        if error is not None:
            sets.append("error = %s")
            params.append(error)
        if run_manifest is not None:
            sets.append("run_manifest = %s")
            params.append(Json(run_manifest))
        if status in ('completed', 'failed'):
            sets.append("completed_at = NOW()")

        params.append(run_id)
        with self._get_conn().cursor() as cur:
            cur.execute(
                f"UPDATE agent_runs SET {', '.join(sets)} WHERE run_id = %s",
                params
            )

    # ------------------------------------------------------------------
    # Step operations
    # ------------------------------------------------------------------

    def create_step(self, run_id: str, step_name: str, step_index: int) -> None:
        """Initialize a step record."""
        with self._get_conn().cursor() as cur:
            cur.execute(
                "INSERT INTO agent_steps (run_id, step_name, step_index, status) "
                "VALUES (%s, %s, %s, 'pending')",
                (run_id, step_name, step_index)
            )

    def update_step(self, run_id: str, step_name: str, status: str,
                    iterations: Optional[int] = None,
                    tool_calls: Optional[int] = None,
                    summary: Optional[str] = None,
                    artifacts: Optional[list] = None,
                    duration_s: Optional[float] = None,
                    error: Optional[str] = None) -> None:
        """Update step status."""
        sets = ["status = %s"]
        params = [status]

        if status == 'running':
            sets.append("started_at = NOW()")
        if status in ('completed', 'failed'):
            sets.append("completed_at = NOW()")
        if iterations is not None:
            sets.append("iterations = %s")
            params.append(iterations)
        if tool_calls is not None:
            sets.append("tool_calls = %s")
            params.append(tool_calls)
        if summary is not None:
            sets.append("summary = %s")
            params.append(summary)
        if artifacts is not None:
            sets.append("artifacts = %s")
            params.append(Json(artifacts))
        if duration_s is not None:
            sets.append("duration_s = %s")
            params.append(duration_s)
        if error is not None:
            sets.append("error = %s")
            params.append(error)

        params.extend([run_id, step_name])
        with self._get_conn().cursor() as cur:
            cur.execute(
                f"UPDATE agent_steps SET {', '.join(sets)} WHERE run_id = %s AND step_name = %s",
                params
            )

    # ------------------------------------------------------------------
    # Event logging (tool calls, reasoning, results)
    # ------------------------------------------------------------------

    def log_event(self, run_id: str, step_name: str,
                  event_type: str, payload: dict) -> int:
        """Log a tool call or reasoning event. Returns the event ID."""
        with self._get_conn().cursor() as cur:
            cur.execute(
                "INSERT INTO agent_events (run_id, step_name, event_type, payload) "
                "VALUES (%s, %s, %s, %s) RETURNING id",
                (run_id, step_name, event_type, Json(payload))
            )
            return cur.fetchone()[0]

    def get_events_since(self, run_id: str, after_id: int = 0, limit: int = 100) -> list:
        """Get events after a given ID (for SSE polling)."""
        with self._get_conn().cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute(
                "SELECT id, step_name, event_type, payload, created_at "
                "FROM agent_events WHERE run_id = %s AND id > %s "
                "ORDER BY id LIMIT %s",
                (run_id, after_id, limit)
            )
            rows = cur.fetchall()
            return [dict(r) for r in rows]

    # ------------------------------------------------------------------
    # Query operations
    # ------------------------------------------------------------------

    def get_run(self, run_id: str) -> Optional[dict]:
        """Get a run with its steps."""
        with self._get_conn().cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute("SELECT * FROM agent_runs WHERE run_id = %s", (run_id,))
            run = cur.fetchone()
            if not run:
                return None
            run = dict(run)

            cur.execute(
                "SELECT * FROM agent_steps WHERE run_id = %s ORDER BY step_index",
                (run_id,)
            )
            run['steps'] = [dict(r) for r in cur.fetchall()]
            return run

    def list_runs(self, domain: Optional[str] = None, limit: int = 20) -> list:
        """List recent runs, newest first."""
        with self._get_conn().cursor(cursor_factory=RealDictCursor) as cur:
            if domain:
                cur.execute(
                    "SELECT * FROM agent_runs WHERE domain = %s "
                    "ORDER BY created_at DESC LIMIT %s",
                    (domain, limit)
                )
            else:
                cur.execute(
                    "SELECT * FROM agent_runs ORDER BY created_at DESC LIMIT %s",
                    (limit,)
                )
            return [dict(r) for r in cur.fetchall()]

    def save_run_manifest(self, run_id: str, manifest: dict) -> None:
        """Persist the run_manifest.json content to the run record."""
        with self._get_conn().cursor() as cur:
            cur.execute(
                "UPDATE agent_runs SET run_manifest = %s WHERE run_id = %s",
                (Json(manifest), run_id)
            )
