-- Databricks notebook source
-- DBTITLE 1,DDL — aibi_member_claims
-- Generated from ERD. Edit catalog/schema in accelerator.yaml only.
-- This is a SQL notebook — each cell is plain SQL separated by:
-- "-- COMMAND ----------"

CREATE SCHEMA IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims;

-- COMMAND ----------

-- DBTITLE 1,Create dim_member_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_member_v6 (
  member_sk BIGINT NOT NULL COMMENT 'Primary key for member dimension.',
  mbr_source_member_id STRING COMMENT 'Source member identifier.',
  mbr_member_id INT COMMENT 'Member identifier from source system.',
  mbr_deers_beneficiary_id STRING COMMENT 'DEERS beneficiary identifier.',
  mbr_deers_family_id STRING COMMENT 'DEERS family identifier.',
  mbr_sponsor_ssn STRING COMMENT 'Sponsor SSN.',
  mbr_current_pcp_eff_date DATE COMMENT 'Current PCP effective date.',
  mbr_current_pcp_nbr STRING COMMENT 'Current PCP number.',
  mbr_dob DATE COMMENT 'Member date of birth.',
  mbr_race STRING COMMENT 'Member race.',
  mbr_sex STRING COMMENT 'Member sex.',
  mbr_ethnicity STRING COMMENT 'Member ethnicity.',
  mbr_first_name STRING COMMENT 'Member first name.',
  mbr_middle_name STRING COMMENT 'Member middle name.',
  mbr_last_name STRING COMMENT 'Member last name.',
  mbr_full_name STRING COMMENT 'Member full name.',
  mbr_marital_status STRING COMMENT 'Member marital status.',
  mbr_deceased_date DATE COMMENT 'Member deceased date.',
  mbr_email STRING COMMENT 'Member email address.',
  mbr_phone_nbr STRING COMMENT 'Member phone number.',
  mbr_mobile_nbr STRING COMMENT 'Member mobile number.',
  mbr_work_nbr STRING COMMENT 'Member work phone number.',
  mbr_sub_group_cd STRING COMMENT 'Member subgroup code.',
  mbr_idcard_issue_date DATE COMMENT 'Member ID card issue date.',
  mbr_line_of_business STRING COMMENT 'Member line of business.',
  mbr_text_opt_in STRING COMMENT 'Member text opt-in indicator.',
  mbr_current_riders STRING COMMENT 'Current riders.',
  mbr_authorized_rep STRING COMMENT 'Authorized representative.',
  mbr_alt_sub_nbr STRING COMMENT 'Alternate subscriber number.',
  mbr_relationship_type STRING COMMENT 'Member relationship type.',
  mbr_salary_tier STRING COMMENT 'Member salary tier.',
  mbr_pcp_auto_assigned STRING COMMENT 'PCP auto-assigned indicator.',
  mbr_secured_flag STRING COMMENT 'Secured flag.',
  mbr_pharmacy_discount_flag STRING COMMENT 'Pharmacy discount flag.',
  mbr_employee_id STRING COMMENT 'Employee identifier.',
  mbr_line_of_business_name STRING COMMENT 'Line of business name.',
  mbr_responsible_party_id STRING COMMENT 'Responsible party identifier.',
  mbr_responsible_party_name STRING COMMENT 'Responsible party name.',
  mbr_deceased_flag STRING COMMENT 'Deceased flag.',
  mbr_pcp_lock_in_indicator STRING COMMENT 'PCP lock-in indicator.',
  mbr_alt_person_nbr STRING COMMENT 'Alternate person number.',
  mbr_state STRING COMMENT 'Member state.',
  mbr_zip_code STRING COMMENT 'Member ZIP code.',
  mbr_pcp_lock_in_type STRING COMMENT 'PCP lock-in type.',
  mbr_provider_group_name STRING COMMENT 'Provider group name.',
  mbr_name_suffix STRING COMMENT 'Member name suffix.',
  mbr_sub_flag INT COMMENT 'Subscriber flag.',
  mbr_sub_ssn STRING COMMENT 'Subscriber SSN.',
  mbr_extract_date DATE COMMENT 'Member extract date.',
  mbr_medicaid_case_nbr STRING COMMENT 'Medicaid case number.',
  mbr_relationship_ind STRING COMMENT 'Relationship indicator.',
  source_system_code STRING COMMENT 'Source system code.',
  source_system_name STRING COMMENT 'Source system name.',
  record_hash STRING COMMENT 'Record hash for change detection.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  end_date TIMESTAMP COMMENT 'Record end timestamp.',
  CONSTRAINT pk_dim_member_v6 PRIMARY KEY (member_sk)
)
COMMENT 'Member dimension table containing current member demographic and profile attributes.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_address_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_address_v6 (
  address_key BIGINT NOT NULL COMMENT 'Primary key for address dimension.',
  entity_type_key STRING COMMENT 'Type of entity associated with the address.',
  entity_dimension_key BIGINT COMMENT 'References dim_member_v6.member_sk.',
  address_type_code STRING COMMENT 'Address type code.',
  street_address_1 STRING COMMENT 'Street address line 1.',
  street_address_2 STRING COMMENT 'Street address line 2.',
  city STRING COMMENT 'City.',
  state STRING COMMENT 'State.',
  zip_code STRING COMMENT 'ZIP code.',
  country_code STRING COMMENT 'Country code.',
  county STRING COMMENT 'County.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  valid_from_date TIMESTAMP COMMENT 'Address validity start timestamp.',
  valid_to_date TIMESTAMP COMMENT 'Address validity end timestamp.',
  source_system_code STRING COMMENT 'Source system code.',
  source_system_name STRING COMMENT 'Source system name.',
  record_hash STRING COMMENT 'Record hash for change detection.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  CONSTRAINT pk_dim_address_v6 PRIMARY KEY (address_key)
)
COMMENT 'Address dimension table containing address records for members and other entities.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_provider_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_provider_v6 (
  provider_sk BIGINT NOT NULL COMMENT 'Primary key for provider dimension.',
  assigned_provider_sk BIGINT COMMENT 'Assigned provider surrogate key.',
  source_provider_id STRING COMMENT 'Source provider identifier.',
  provider_npi STRING COMMENT 'Provider National Provider Identifier.',
  provider_tax_id STRING COMMENT 'Provider tax identifier.',
  provider_name STRING COMMENT 'Provider name.',
  provider_address_sk BIGINT COMMENT 'References dim_address_v6.address_key.',
  pcp_flag BOOLEAN COMMENT 'Primary care provider indicator.',
  affiliation_id STRING COMMENT 'Provider affiliation identifier.',
  valid_from_date TIMESTAMP COMMENT 'Provider record validity start timestamp.',
  valid_to_date TIMESTAMP COMMENT 'Provider record validity end timestamp.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  source_system STRING COMMENT 'Source system.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  last_update_dt TIMESTAMP COMMENT 'Last update timestamp.',
  record_hash STRING COMMENT 'Record hash for change detection.',
  CONSTRAINT pk_dim_provider_v6 PRIMARY KEY (provider_sk)
)
COMMENT 'Provider dimension table containing provider identity, affiliation, PCP, and address attributes.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_member_identifier_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_member_identifier_v6 (
  mbr_identifier_sk BIGINT NOT NULL COMMENT 'Primary key for member identifier dimension.',
  member_sk BIGINT COMMENT 'References dim_member_v6.member_sk.',
  id_type STRING COMMENT 'Identifier type.',
  id_value STRING COMMENT 'Identifier value.',
  source_system_code STRING COMMENT 'Source system code.',
  source_system_name STRING COMMENT 'Source system name.',
  valid_to_date TIMESTAMP COMMENT 'Identifier validity end timestamp.',
  valid_from_date TIMESTAMP COMMENT 'Identifier validity start timestamp.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  record_hash STRING COMMENT 'Record hash for change detection.',
  CONSTRAINT pk_dim_member_identifier_v6 PRIMARY KEY (mbr_identifier_sk)
)
COMMENT 'Member identifier dimension table containing alternate and source-specific member identifiers.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_member_history_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_member_history_v6 (
  mbr_history_sk BIGINT NOT NULL COMMENT 'Primary key for member history dimension.',
  member_sk BIGINT COMMENT 'References dim_member_v6.member_sk.',
  mbr_source_member_id STRING COMMENT 'Source member identifier.',
  mbr_member_id INT COMMENT 'Member identifier from source system.',
  mbr_deers_beneficiary_id STRING COMMENT 'DEERS beneficiary identifier.',
  mbr_deers_family_id STRING COMMENT 'DEERS family identifier.',
  mbr_sponsor_ssn STRING COMMENT 'Sponsor SSN.',
  mbr_current_pcp_eff_date DATE COMMENT 'Current PCP effective date.',
  mbr_current_pcp_nbr STRING COMMENT 'Current PCP number.',
  mbr_dob DATE COMMENT 'Member date of birth.',
  mbr_race STRING COMMENT 'Member race.',
  mbr_sex STRING COMMENT 'Member sex.',
  mbr_ethnicity STRING COMMENT 'Member ethnicity.',
  mbr_first_name STRING COMMENT 'Member first name.',
  mbr_middle_name STRING COMMENT 'Member middle name.',
  mbr_last_name STRING COMMENT 'Member last name.',
  mbr_full_name STRING COMMENT 'Member full name.',
  mbr_marital_status STRING COMMENT 'Member marital status.',
  mbr_deceased_date DATE COMMENT 'Member deceased date.',
  mbr_email STRING COMMENT 'Member email address.',
  mbr_phone_nbr STRING COMMENT 'Member phone number.',
  mbr_mobile_nbr STRING COMMENT 'Member mobile number.',
  mbr_work_nbr STRING COMMENT 'Member work phone number.',
  mbr_sub_group_cd STRING COMMENT 'Member subgroup code.',
  mbr_idcard_issue_date DATE COMMENT 'Member ID card issue date.',
  mbr_line_of_business STRING COMMENT 'Member line of business.',
  mbr_text_opt_in STRING COMMENT 'Member text opt-in indicator.',
  mbr_current_riders STRING COMMENT 'Current riders.',
  mbr_authorized_rep STRING COMMENT 'Authorized representative.',
  mbr_alt_sub_nbr STRING COMMENT 'Alternate subscriber number.',
  mbr_relationship_type STRING COMMENT 'Member relationship type.',
  mbr_salary_tier STRING COMMENT 'Member salary tier.',
  mbr_pcp_auto_assigned STRING COMMENT 'PCP auto-assigned indicator.',
  mbr_secured_flag STRING COMMENT 'Secured flag.',
  mbr_pharmacy_discount_flag STRING COMMENT 'Pharmacy discount flag.',
  mbr_employee_id STRING COMMENT 'Employee identifier.',
  mbr_line_of_business_name STRING COMMENT 'Line of business name.',
  mbr_responsible_party_id STRING COMMENT 'Responsible party identifier.',
  mbr_responsible_party_name STRING COMMENT 'Responsible party name.',
  mbr_deceased_flag STRING COMMENT 'Deceased flag.',
  mbr_pcp_lock_in_indicator STRING COMMENT 'PCP lock-in indicator.',
  mbr_alt_person_nbr STRING COMMENT 'Alternate person number.',
  mbr_state STRING COMMENT 'Member state.',
  mbr_zip_code STRING COMMENT 'Member ZIP code.',
  mbr_pcp_lock_in_type STRING COMMENT 'PCP lock-in type.',
  mbr_provider_group_name STRING COMMENT 'Provider group name.',
  mbr_name_suffix STRING COMMENT 'Member name suffix.',
  mbr_sub_flag INT COMMENT 'Subscriber flag.',
  mbr_sub_ssn STRING COMMENT 'Subscriber SSN.',
  mbr_extract_date DATE COMMENT 'Member extract date.',
  mbr_medicaid_case_nbr STRING COMMENT 'Medicaid case number.',
  mbr_relationship_ind STRING COMMENT 'Relationship indicator.',
  source_system_code STRING COMMENT 'Source system code.',
  source_system_name STRING COMMENT 'Source system name.',
  record_hash STRING COMMENT 'Record hash for change detection.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  valid_to_date TIMESTAMP COMMENT 'History validity end timestamp.',
  valid_from_date TIMESTAMP COMMENT 'History validity start timestamp.',
  CONSTRAINT pk_dim_member_history_v6 PRIMARY KEY (mbr_history_sk)
)
COMMENT 'Member history dimension table containing historical member demographic and profile attributes.';

-- COMMAND ----------

-- DBTITLE 1,Create fact_claim_header_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.fact_claim_header_v6 (
  clm_header_sk BIGINT NOT NULL COMMENT 'Primary key for claim header fact.',
  clm_id INT COMMENT 'Claim internal identifier.',
  clm_claim_id STRING COMMENT 'Claim identifier referenced by fact_claim_detail_v6.clm_dtl_claim_id.',
  clm_original_source_claim_id STRING COMMENT 'Original source claim identifier.',
  clm_original_batch_nbr STRING COMMENT 'Original batch number.',
  clm_patient_control_nbr STRING COMMENT 'Patient control number.',
  clm_document_adj_control_nbr STRING COMMENT 'Document adjustment control number.',
  clm_claim_type STRING COMMENT 'Claim type.',
  clm_bill_type STRING COMMENT 'Bill type.',
  clm_authorization_nbr STRING COMMENT 'Authorization number.',
  clm_ext_authorization_nbr STRING COMMENT 'External authorization number.',
  clm_admit_date DATE COMMENT 'Claim admit date.',
  clm_claim_thru_date DATE COMMENT 'Claim through date.',
  clm_discharge_date DATE COMMENT 'Discharge date.',
  clm_admission_hour INT COMMENT 'Admission hour.',
  clm_discharge_hour INT COMMENT 'Discharge hour.',
  clm_admission_type STRING COMMENT 'Admission type.',
  clm_admission_source STRING COMMENT 'Admission source.',
  clm_member_nbr STRING COMMENT 'Member number.',
  clm_member_name STRING COMMENT 'Member name.',
  clm_member_sk BIGINT COMMENT 'References dim_member_v6.member_sk.',
  clm_member_group_nbr STRING COMMENT 'Member group number.',
  clm_member_subgroup_nbr STRING COMMENT 'Member subgroup number.',
  clm_plan_code STRING COMMENT 'Plan code.',
  clm_line_of_business STRING COMMENT 'Line of business.',
  clm_birth_weight DECIMAL(9,2) COMMENT 'Birth weight.',
  clm_covered_days INT COMMENT 'Covered days.',
  clm_accident_st STRING COMMENT 'Accident state.',
  clm_attending_physician STRING COMMENT 'Attending physician.',
  clm_attending_physician_spec STRING COMMENT 'Attending physician specialty.',
  clm_operating_provider_name STRING COMMENT 'Operating provider name.',
  clm_operating_provider_npi STRING COMMENT 'Operating provider NPI.',
  clm_submitting_provider STRING COMMENT 'Submitting provider.',
  clm_submitting_provider_spec STRING COMMENT 'Submitting provider specialty.',
  clm_submitting_provider_type STRING COMMENT 'Submitting provider type.',
  clm_billing_provider STRING COMMENT 'Billing provider.',
  clm_referring_provider STRING COMMENT 'Referring provider.',
  clm_referring_provider_spec STRING COMMENT 'Referring provider specialty.',
  clm_referring_provider_type STRING COMMENT 'Referring provider type.',
  clm_is_par_submitting_provider STRING COMMENT 'Participating submitting provider indicator.',
  clm_is_par_referring_provider BOOLEAN COMMENT 'Participating referring provider indicator.',
  clm_is_par_rendering_provider BOOLEAN COMMENT 'Participating rendering provider indicator.',
  clm_assigned_pcp STRING COMMENT 'Assigned PCP.',
  clm_assigned_provider_site STRING COMMENT 'Assigned provider site.',
  clm_insurance_id STRING COMMENT 'Insurance identifier.',
  clm_member_contract_id STRING COMMENT 'Member contract identifier.',
  clm_pcp_visit_flag INT COMMENT 'PCP visit flag.',
  clm_pcp_in_type STRING COMMENT 'PCP in type.',
  clm_pcp_wthld_pct DECIMAL(9,4) COMMENT 'PCP withheld percentage.',
  clm_service_fac_npi STRING COMMENT 'Service facility NPI.',
  clm_service_fac_loc_name STRING COMMENT 'Service facility location name.',
  clm_service_facility_address_sk BIGINT COMMENT 'References dim_address_v6.address_key.',
  clm_providers_account_no STRING COMMENT 'Provider account number.',
  clm_onset_of_illness_date STRING COMMENT 'Onset of illness date.',
  clm_admitting_diagnosis_code STRING COMMENT 'Admitting diagnosis code.',
  clm_admitting_diagnosis_method STRING COMMENT 'Admitting diagnosis coding method.',
  clm_diagnosis_1 STRING COMMENT 'Diagnosis code 1.',
  clm_diagnosis_1_icd_method STRING COMMENT 'Diagnosis 1 ICD method.',
  clm_diagnosis_2 STRING COMMENT 'Diagnosis code 2.',
  clm_diagnosis_2_icd_method STRING COMMENT 'Diagnosis 2 ICD method.',
  clm_diagnosis_3 STRING COMMENT 'Diagnosis code 3.',
  clm_diagnosis_3_icd_method STRING COMMENT 'Diagnosis 3 ICD method.',
  clm_diagnosis_4 STRING COMMENT 'Diagnosis code 4.',
  clm_diagnosis_4_icd_method STRING COMMENT 'Diagnosis 4 ICD method.',
  clm_diagnosis_5 STRING COMMENT 'Diagnosis code 5.',
  clm_diagnosis_5_icd_method STRING COMMENT 'Diagnosis 5 ICD method.',
  clm_diagnosis_6 STRING COMMENT 'Diagnosis code 6.',
  clm_diagnosis_6_icd_method STRING COMMENT 'Diagnosis 6 ICD method.',
  clm_diagnosis_7 STRING COMMENT 'Diagnosis code 7.',
  clm_diagnosis_7_icd_method STRING COMMENT 'Diagnosis 7 ICD method.',
  clm_diagnosis_8 STRING COMMENT 'Diagnosis code 8.',
  clm_diagnosis_8_icd_method STRING COMMENT 'Diagnosis 8 ICD method.',
  clm_diagnosis_9 STRING COMMENT 'Diagnosis code 9.',
  clm_diagnosis_9_icd_method STRING COMMENT 'Diagnosis 9 ICD method.',
  clm_diagnosis_10 STRING COMMENT 'Diagnosis code 10.',
  clm_diagnosis_10_icd_method STRING COMMENT 'Diagnosis 10 ICD method.',
  clm_diagnosis_11 STRING COMMENT 'Diagnosis code 11.',
  clm_diagnosis_11_icd_method STRING COMMENT 'Diagnosis 11 ICD method.',
  clm_diagnosis_12 STRING COMMENT 'Diagnosis code 12.',
  clm_diagnosis_12_icd_method STRING COMMENT 'Diagnosis 12 ICD method.',
  clm_diagnosis_13 STRING COMMENT 'Diagnosis code 13.',
  clm_diagnosis_13_icd_method STRING COMMENT 'Diagnosis 13 ICD method.',
  clm_diagnosis_14 STRING COMMENT 'Diagnosis code 14.',
  clm_diagnosis_14_icd_method STRING COMMENT 'Diagnosis 14 ICD method.',
  clm_diagnosis_15 STRING COMMENT 'Diagnosis code 15.',
  clm_diagnosis_15_icd_method STRING COMMENT 'Diagnosis 15 ICD method.',
  clm_diagnosis_16 STRING COMMENT 'Diagnosis code 16.',
  clm_diagnosis_16_icd_method STRING COMMENT 'Diagnosis 16 ICD method.',
  clm_diagnosis_17 STRING COMMENT 'Diagnosis code 17.',
  clm_diagnosis_17_icd_method STRING COMMENT 'Diagnosis 17 ICD method.',
  clm_diagnosis_18 STRING COMMENT 'Diagnosis code 18.',
  clm_diagnosis_18_icd_method STRING COMMENT 'Diagnosis 18 ICD method.',
  clm_diagnosis_19 STRING COMMENT 'Diagnosis code 19.',
  clm_diagnosis_19_icd_method STRING COMMENT 'Diagnosis 19 ICD method.',
  clm_diagnosis_20 STRING COMMENT 'Diagnosis code 20.',
  clm_diagnosis_20_icd_method STRING COMMENT 'Diagnosis 20 ICD method.',
  clm_diagnosis_21 STRING COMMENT 'Diagnosis code 21.',
  clm_diagnosis_21_icd_method STRING COMMENT 'Diagnosis 21 ICD method.',
  clm_diagnosis_22 STRING COMMENT 'Diagnosis code 22.',
  clm_diagnosis_22_icd_method STRING COMMENT 'Diagnosis 22 ICD method.',
  clm_diagnosis_23 STRING COMMENT 'Diagnosis code 23.',
  clm_diagnosis_23_icd_method STRING COMMENT 'Diagnosis 23 ICD method.',
  clm_diagnosis_24 STRING COMMENT 'Diagnosis code 24.',
  clm_diagnosis_24_icd_method STRING COMMENT 'Diagnosis 24 ICD method.',
  clm_diagnosis_25 STRING COMMENT 'Diagnosis code 25.',
  clm_diagnosis_25_icd_method STRING COMMENT 'Diagnosis 25 ICD method.',
  clm_diagnosis_1_poa STRING COMMENT 'Diagnosis 1 present-on-admission indicator.',
  clm_diagnosis_2_poa STRING COMMENT 'Diagnosis 2 present-on-admission indicator.',
  clm_diagnosis_3_poa STRING COMMENT 'Diagnosis 3 present-on-admission indicator.',
  clm_diagnosis_4_poa STRING COMMENT 'Diagnosis 4 present-on-admission indicator.',
  clm_diagnosis_5_poa STRING COMMENT 'Diagnosis 5 present-on-admission indicator.',
  clm_diagnosis_6_poa STRING COMMENT 'Diagnosis 6 present-on-admission indicator.',
  clm_diagnosis_7_poa STRING COMMENT 'Diagnosis 7 present-on-admission indicator.',
  clm_diagnosis_8_poa STRING COMMENT 'Diagnosis 8 present-on-admission indicator.',
  clm_diagnosis_9_poa STRING COMMENT 'Diagnosis 9 present-on-admission indicator.',
  clm_diagnosis_10_poa STRING COMMENT 'Diagnosis 10 present-on-admission indicator.',
  clm_diagnosis_11_poa STRING COMMENT 'Diagnosis 11 present-on-admission indicator.',
  clm_diagnosis_12_poa STRING COMMENT 'Diagnosis 12 present-on-admission indicator.',
  clm_diagnosis_13_poa STRING COMMENT 'Diagnosis 13 present-on-admission indicator.',
  clm_diagnosis_14_poa STRING COMMENT 'Diagnosis 14 present-on-admission indicator.',
  clm_diagnosis_15_poa STRING COMMENT 'Diagnosis 15 present-on-admission indicator.',
  clm_diagnosis_16_poa STRING COMMENT 'Diagnosis 16 present-on-admission indicator.',
  clm_diagnosis_17_poa STRING COMMENT 'Diagnosis 17 present-on-admission indicator.',
  clm_diagnosis_18_poa STRING COMMENT 'Diagnosis 18 present-on-admission indicator.',
  clm_diagnosis_19_poa STRING COMMENT 'Diagnosis 19 present-on-admission indicator.',
  clm_diagnosis_20_poa STRING COMMENT 'Diagnosis 20 present-on-admission indicator.',
  clm_diagnosis_21_poa STRING COMMENT 'Diagnosis 21 present-on-admission indicator.',
  clm_diagnosis_22_poa STRING COMMENT 'Diagnosis 22 present-on-admission indicator.',
  clm_diagnosis_23_poa STRING COMMENT 'Diagnosis 23 present-on-admission indicator.',
  clm_diagnosis_24_poa STRING COMMENT 'Diagnosis 24 present-on-admission indicator.',
  clm_diagnosis_25_poa STRING COMMENT 'Diagnosis 25 present-on-admission indicator.',
  clm_surgical_1 STRING COMMENT 'Surgical procedure code 1.',
  clm_surgical_icd_method_1 STRING COMMENT 'Surgical procedure 1 ICD method.',
  clm_surgical_2 STRING COMMENT 'Surgical procedure code 2.',
  clm_surgical_icd_method_2 STRING COMMENT 'Surgical procedure 2 ICD method.',
  clm_surgical_3 STRING COMMENT 'Surgical procedure code 3.',
  clm_surgical_icd_method_3 STRING COMMENT 'Surgical procedure 3 ICD method.',
  clm_surgical_4 STRING COMMENT 'Surgical procedure code 4.',
  clm_surgical_icd_method_4 STRING COMMENT 'Surgical procedure 4 ICD method.',
  clm_surgical_5 STRING COMMENT 'Surgical procedure code 5.',
  clm_surgical_icd_method_5 STRING COMMENT 'Surgical procedure 5 ICD method.',
  clm_surgical_6 STRING COMMENT 'Surgical procedure code 6.',
  clm_surgical_icd_method_6 STRING COMMENT 'Surgical procedure 6 ICD method.',
  clm_drg_code STRING COMMENT 'DRG code.',
  clm_service_type_code STRING COMMENT 'Service type code.',
  clm_cob_type STRING COMMENT 'Coordination of benefits type.',
  clm_claim_timely_filing STRING COMMENT 'Timely filing indicator.',
  clm_accept_assignment_indicator STRING COMMENT 'Accept assignment indicator.',
  clm_add_date DATE COMMENT 'Claim add date.',
  clm_add_user STRING COMMENT 'Claim add user.',
  clm_update_date DATE COMMENT 'Claim update date.',
  clm_update_user STRING COMMENT 'Claim update user.',
  clm_extract_date TIMESTAMP COMMENT 'Claim extract timestamp.',
  clm_last_updated_date DATE COMMENT 'Claim last updated date.',
  clm_original_insert_date DATE COMMENT 'Claim original insert date.',
  clm_user_id STRING COMMENT 'Claim user identifier.',
  clm_orig_source STRING COMMENT 'Claim original source.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  end_date TIMESTAMP COMMENT 'Record end timestamp.',
  record_hash STRING COMMENT 'Record hash for change detection.',
  last_updated_date DATE COMMENT 'Last updated date.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  source_system_code STRING COMMENT 'Source system code.',
  source_system_name STRING COMMENT 'Source system name.',
  CONSTRAINT pk_fact_claim_header_v6 PRIMARY KEY (clm_header_sk)
)
COMMENT 'Claim header fact table containing claim-level attributes, member references, provider attributes, diagnoses, procedures, and source metadata.';

-- COMMAND ----------

-- DBTITLE 1,Create fact_claim_detail_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.fact_claim_detail_v6 (
  clm_dtl_claim_id STRING COMMENT 'References fact_claim_header_v6.clm_claim_id.',
  clm_dtl_line_nbr STRING COMMENT 'Claim detail line number.',
  clm_dtl_original_source_claim_id STRING COMMENT 'Original source claim identifier for claim detail.',
  clm_dtl_source_system STRING COMMENT 'Claim detail source system.',
  clm_dtl_member_nbr_sk STRING COMMENT 'Claim detail member number surrogate key.',
  clmdetail_admit_dt TIMESTAMP COMMENT 'Claim detail admit timestamp.',
  clm_dtl_specific_dos_date DATE COMMENT 'Specific date of service.',
  clm_dtl_specific_dos_thru_date DATE COMMENT 'Specific through date of service.',
  clm_dtl_ap_posting_date DATE COMMENT 'Accounts payable posting date.',
  clm_dtl_claim_receive_date TIMESTAMP COMMENT 'Claim received timestamp.',
  clm_dtl_check_date TIMESTAMP COMMENT 'Check timestamp.',
  clm_dtl_last_update_date TIMESTAMP COMMENT 'Claim detail last update timestamp.',
  clm_dtl_benefit_category STRING COMMENT 'Benefit category.',
  clm_dtl_benefit_level STRING COMMENT 'Benefit level.',
  clm_dtl_claim_type STRING COMMENT 'Claim type.',
  clm_dtl_allowed_amt DECIMAL(28,4) COMMENT 'Allowed amount.',
  clm_dtl_billed_amt DECIMAL(27,4) COMMENT 'Billed amount.',
  clm_dtl_deduct_amt DECIMAL(27,4) COMMENT 'Deductible amount.',
  clm_dtl_net_amt DECIMAL(28,4) COMMENT 'Net amount.',
  clm_dtl_paid_amt DECIMAL(28,4) COMMENT 'Paid amount.',
  clm_dtl_actual_paid_amt DECIMAL(38,4) COMMENT 'Actual paid amount.',
  clm_dtl_not_covered_amt DECIMAL(27,4) COMMENT 'Not covered amount.',
  clm_dtl_co_insurance_amt DECIMAL(27,4) COMMENT 'Coinsurance amount.',
  clm_dtl_other_adjustments_amt DECIMAL(30,2) COMMENT 'Other adjustments amount.',
  clm_dtl_cob_savings DECIMAL(32,4) COMMENT 'Coordination of benefits savings.',
  clm_dtl_oic_paid_amt DECIMAL(19,4) COMMENT 'OIC paid amount.',
  clm_dtl_oic_allowed_amt DECIMAL(19,4) COMMENT 'OIC allowed amount.',
  clm_dtl_interest_amt DECIMAL(38,6) COMMENT 'Interest amount.',
  clm_dtl_prompt_pay_discount_amt DECIMAL(20,4) COMMENT 'Prompt pay discount amount.',
  clm_dtl_interest_discount_amt DECIMAL(38,6) COMMENT 'Interest discount amount.',
  clm_dtl_interest_discount_flag STRING COMMENT 'Interest discount flag.',
  clm_dtl_copay_amt DECIMAL(27,4) COMMENT 'Copay amount.',
  clm_dtl_copay_reason STRING COMMENT 'Copay reason.',
  clm_dtl_st_cd STRING COMMENT 'State code.',
  clm_dtl_reason_code_sk STRING COMMENT 'Reason code surrogate key.',
  clm_dtl_line_status STRING COMMENT 'Claim detail line status.',
  clm_dtl_clean_claim_ind STRING COMMENT 'Clean claim indicator.',
  clm_dtl_place_of_service STRING COMMENT 'Place of service.',
  clm_dtl_fee_schedule_code STRING COMMENT 'Fee schedule code.',
  clm_dtl_authorization_nbr STRING COMMENT 'Authorization number.',
  clm_dtl_check_nbr STRING COMMENT 'Check number.',
  clm_dtl_check_added_line_flag STRING COMMENT 'Check added line flag.',
  clm_dtl_check_message STRING COMMENT 'Check message.',
  clm_dtl_submitting_provider STRING COMMENT 'Submitting provider.',
  clm_dtl_rendering_provider STRING COMMENT 'Rendering provider.',
  clm_dtl_rendering_provider_type STRING COMMENT 'Rendering provider type.',
  clm_dtl_rendering_provider_spec STRING COMMENT 'Rendering provider specialty.',
  clm_dtl_participating_provider STRING COMMENT 'Participating provider.',
  clm_dtl_adjudication_status STRING COMMENT 'Adjudication status.',
  clm_dtl_procedure_code STRING COMMENT 'Procedure code.',
  clm_dtl_procedure_modifier STRING COMMENT 'Procedure modifier.',
  clm_dtl_modifier_2 STRING COMMENT 'Procedure modifier 2.',
  clm_dtl_modifier_3 STRING COMMENT 'Procedure modifier 3.',
  clm_dtl_modifier_4 STRING COMMENT 'Procedure modifier 4.',
  clm_dtl_procedure_adj STRING COMMENT 'Procedure adjustment.',
  clm_dtl_procedure_qty DECIMAL(15,3) COMMENT 'Procedure quantity.',
  clm_dtl_revenue_code STRING COMMENT 'Revenue code.',
  clm_dtl_diagnosis_ind_1 STRING COMMENT 'Diagnosis indicator 1.',
  clm_dtl_diagnosis_ind_2 STRING COMMENT 'Diagnosis indicator 2.',
  clm_dtl_diagnosis_ind_3 STRING COMMENT 'Diagnosis indicator 3.',
  clm_dtl_diagnosis_ind_4 STRING COMMENT 'Diagnosis indicator 4.',
  clm_dtl_paid_days DECIMAL(36,3) COMMENT 'Paid days.',
  clm_dtl_anesthesia_time_units DECIMAL(12,2) COMMENT 'Anesthesia time units.',
  clm_dtl_cob_rule STRING COMMENT 'Coordination of benefits rule.',
  clm_dtl_wrap_network STRING COMMENT 'Wrap network.',
  clm_dtl_returned_ntwrk_repric STRING COMMENT 'Returned network repricing indicator.',
  clm_dtl_user_id STRING COMMENT 'Claim detail user identifier.',
  clm_dtl_extract_date TIMESTAMP COMMENT 'Claim detail extract timestamp.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  updated_at TIMESTAMP COMMENT 'Record update timestamp.',
  created_at TIMESTAMP COMMENT 'Record creation timestamp.'
)
COMMENT 'Claim detail fact table containing claim line-level service, financial, procedure, provider, and adjudication attributes.';

-- COMMAND ----------

-- DBTITLE 1,Create fact_member_enrollment_v6
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.fact_member_enrollment_v6 (
  source_system STRING COMMENT 'Source system.',
  src_member_business_id INT COMMENT 'Source member business identifier.',
  mbr_enr_source_member_id STRING COMMENT 'Enrollment source member identifier.',
  mbr_enr_insured_id STRING COMMENT 'Enrollment insured identifier.',
  mbr_enr_contract_id STRING COMMENT 'Enrollment contract identifier.',
  mbr_enr_insured_code STRING COMMENT 'Enrollment insured code.',
  mbr_enr_insured_add_date TIMESTAMP COMMENT 'Insured add timestamp.',
  mbr_enr_insured_event_date TIMESTAMP COMMENT 'Insured event timestamp.',
  mbr_enr_insured_event_id STRING COMMENT 'Insured event identifier.',
  mbr_enr_insured_event_code STRING COMMENT 'Insured event code.',
  mbr_enr_status STRING COMMENT 'Enrollment status.',
  mbr_enr_insured_event_add_date TIMESTAMP COMMENT 'Insured event add timestamp.',
  mbr_enr_plan_id STRING COMMENT 'Enrollment plan identifier.',
  mbr_enr_line_of_business STRING COMMENT 'Enrollment line of business.',
  mbr_enr_line_of_business_id STRING COMMENT 'Enrollment line of business identifier.',
  mbr_enr_group_name STRING COMMENT 'Enrollment group name.',
  mbr_enr_subgroup_name STRING COMMENT 'Enrollment subgroup name.',
  mbr_enr_effective_date DATE COMMENT 'Enrollment effective date.',
  mbr_enr_termination_date DATE COMMENT 'Enrollment termination date.',
  mbr_enr_termination_event_date DATE COMMENT 'Enrollment termination event date.',
  mbr_enr_termination_reason STRING COMMENT 'Enrollment termination reason.',
  mbr_enr_product_id STRING COMMENT 'Enrollment product identifier.',
  mbr_enr_group_ck STRING COMMENT 'Enrollment group check key.',
  mbr_enr_group_code STRING COMMENT 'Enrollment group code.',
  mbr_enr_subgroup_ck STRING COMMENT 'Enrollment subgroup check key.',
  mbr_enr_subgroup_code STRING COMMENT 'Enrollment subgroup code.',
  is_active BOOLEAN COMMENT 'Active record indicator.',
  id_value STRING COMMENT 'Identifier value.',
  id_type STRING COMMENT 'Identifier type.',
  member_sk BIGINT COMMENT 'References dim_member_v6.member_sk.',
  enrollment_sk STRING COMMENT 'Enrollment surrogate key.',
  payload_hash STRING COMMENT 'Payload hash for change detection.'
)
COMMENT 'Member enrollment fact table containing member plan enrollment, group, subgroup, eligibility, and termination attributes.';
