#!/bin/bash -e
if [[ ! -f "/home/spark-165b9780-d26f-40bb-b8a7-8e/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-165b9780-d26f-40bb-b8a7-8e/tmp/uv/uv_0.6.10_linux_amd64" "$@"
