-- Databricks notebook source
-- DBTITLE 1,DDL — aibi_member_claims
-- Generated from ERD. Edit catalog/schema in accelerator.yaml only.
-- This is a SQL notebook — each cell is plain SQL separated by:
-- "-- COMMAND ----------"

CREATE SCHEMA IF NOT EXISTS aw_serverless_stable_catalog.aibi_member_claims;

-- COMMAND ----------

-- DBTITLE 1,Create dim_member_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_member_v2 (
  member_sk BIGINT NOT NULL COMMENT 'Primary key.',
  mbr_source_member_id STRING COMMENT 'Column.',
  mbr_member_id INT COMMENT 'Column.',
  mbr_deers_beneficiary_id STRING COMMENT 'Column.',
  mbr_deers_family_id STRING COMMENT 'Column.',
  mbr_sponsor_ssn STRING COMMENT 'Column.',
  mbr_current_pcp_eff_date DATE COMMENT 'Column.',
  mbr_current_pcp_nbr STRING COMMENT 'Column.',
  mbr_dob DATE COMMENT 'Column.',
  mbr_race STRING COMMENT 'Column.',
  mbr_sex STRING COMMENT 'Column.',
  mbr_ethnicity STRING COMMENT 'Column.',
  mbr_first_name STRING COMMENT 'Column.',
  mbr_middle_name STRING COMMENT 'Column.',
  mbr_last_name STRING COMMENT 'Column.',
  mbr_full_name STRING COMMENT 'Column.',
  mbr_marital_status STRING COMMENT 'Column.',
  mbr_deceased_date DATE COMMENT 'Column.',
  mbr_email STRING COMMENT 'Column.',
  mbr_phone_nbr STRING COMMENT 'Column.',
  mbr_mobile_nbr STRING COMMENT 'Column.',
  mbr_work_nbr STRING COMMENT 'Column.',
  mbr_sub_group_cd STRING COMMENT 'Column.',
  mbr_idcard_issue_date DATE COMMENT 'Column.',
  mbr_line_of_business STRING COMMENT 'Column.',
  mbr_text_opt_in STRING COMMENT 'Column.',
  mbr_current_riders STRING COMMENT 'Column.',
  mbr_authorized_rep STRING COMMENT 'Column.',
  mbr_alt_sub_nbr STRING COMMENT 'Column.',
  mbr_relationship_type STRING COMMENT 'Column.',
  mbr_salary_tier STRING COMMENT 'Column.',
  mbr_pcp_auto_assigned STRING COMMENT 'Column.',
  mbr_secured_flag STRING COMMENT 'Column.',
  mbr_pharmacy_discount_flag STRING COMMENT 'Column.',
  mbr_employee_id STRING COMMENT 'Column.',
  mbr_line_of_business_name STRING COMMENT 'Column.',
  mbr_responsible_party_id STRING COMMENT 'Column.',
  mbr_responsible_party_name STRING COMMENT 'Column.',
  mbr_deceased_flag STRING COMMENT 'Column.',
  mbr_pcp_lock_in_indicator STRING COMMENT 'Column.',
  mbr_alt_person_nbr STRING COMMENT 'Column.',
  mbr_state STRING COMMENT 'Column.',
  mbr_zip_code STRING COMMENT 'Column.',
  mbr_pcp_lock_in_type STRING COMMENT 'Column.',
  mbr_provider_group_name STRING COMMENT 'Column.',
  mbr_name_suffix STRING COMMENT 'Column.',
  mbr_sub_flag INT COMMENT 'Column.',
  mbr_sub_ssn STRING COMMENT 'Column.',
  mbr_extract_date DATE COMMENT 'Column.',
  mbr_medicaid_case_nbr STRING COMMENT 'Column.',
  mbr_relationship_ind STRING COMMENT 'Column.',
  source_system_code STRING COMMENT 'Column.',
  source_system_name STRING COMMENT 'Column.',
  record_hash STRING COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  end_date TIMESTAMP COMMENT 'Column.',
  CONSTRAINT pk_dim_member_v2 PRIMARY KEY (member_sk)
)
COMMENT 'Member dimension table.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_address_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_address_v2 (
  address_key BIGINT NOT NULL COMMENT 'Primary key.',
  entity_type_key STRING COMMENT 'Column.',
  entity_dimension_key BIGINT COMMENT 'References dim_member_v2.member_sk.',
  address_type_code STRING COMMENT 'Column.',
  street_address_1 STRING COMMENT 'Column.',
  street_address_2 STRING COMMENT 'Column.',
  city STRING COMMENT 'Column.',
  state STRING COMMENT 'Column.',
  zip_code STRING COMMENT 'Column.',
  country_code STRING COMMENT 'Column.',
  county STRING COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  valid_from_date TIMESTAMP COMMENT 'Column.',
  valid_to_date TIMESTAMP COMMENT 'Column.',
  source_system_code STRING COMMENT 'Column.',
  source_system_name STRING COMMENT 'Column.',
  record_hash STRING COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  CONSTRAINT pk_dim_address_v2 PRIMARY KEY (address_key)
)
COMMENT 'Address dimension table.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_provider_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_provider_v2 (
  provider_sk BIGINT NOT NULL COMMENT 'Primary key.',
  assigned_provider_sk BIGINT COMMENT 'Column.',
  source_provider_id STRING COMMENT 'Column.',
  provider_npi STRING COMMENT 'Column.',
  provider_tax_id STRING COMMENT 'Column.',
  provider_name STRING COMMENT 'Column.',
  provider_address_sk BIGINT COMMENT 'References dim_address_v2.address_key.',
  pcp_flag BOOLEAN COMMENT 'Column.',
  affiliation_id STRING COMMENT 'Column.',
  valid_from_date TIMESTAMP COMMENT 'Column.',
  valid_to_date TIMESTAMP COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  source_system STRING COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  last_update_dt TIMESTAMP COMMENT 'Column.',
  record_hash STRING COMMENT 'Column.',
  CONSTRAINT pk_dim_provider_v2 PRIMARY KEY (provider_sk)
)
COMMENT 'Provider dimension table.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_member_identifier_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_member_identifier_v2 (
  mbr_identifier_sk BIGINT NOT NULL COMMENT 'Primary key.',
  member_sk BIGINT COMMENT 'References dim_member_v2.member_sk.',
  id_type STRING COMMENT 'Column.',
  id_value STRING COMMENT 'Column.',
  source_system_code STRING COMMENT 'Column.',
  source_system_name STRING COMMENT 'Column.',
  valid_to_date TIMESTAMP COMMENT 'Column.',
  valid_from_date TIMESTAMP COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  record_hash STRING COMMENT 'Column.',
  CONSTRAINT pk_dim_member_identifier_v2 PRIMARY KEY (mbr_identifier_sk)
)
COMMENT 'Member identifier dimension table.';

-- COMMAND ----------

-- DBTITLE 1,Create dim_member_history_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.dim_member_history_v2 (
  mbr_history_sk BIGINT NOT NULL COMMENT 'Primary key.',
  member_sk BIGINT COMMENT 'References dim_member_v2.member_sk.',
  mbr_source_member_id STRING COMMENT 'Column.',
  mbr_member_id INT COMMENT 'Column.',
  mbr_deers_beneficiary_id STRING COMMENT 'Column.',
  mbr_deers_family_id STRING COMMENT 'Column.',
  mbr_sponsor_ssn STRING COMMENT 'Column.',
  mbr_current_pcp_eff_date DATE COMMENT 'Column.',
  mbr_current_pcp_nbr STRING COMMENT 'Column.',
  mbr_dob DATE COMMENT 'Column.',
  mbr_race STRING COMMENT 'Column.',
  mbr_sex STRING COMMENT 'Column.',
  mbr_ethnicity STRING COMMENT 'Column.',
  mbr_first_name STRING COMMENT 'Column.',
  mbr_middle_name STRING COMMENT 'Column.',
  mbr_last_name STRING COMMENT 'Column.',
  mbr_full_name STRING COMMENT 'Column.',
  mbr_marital_status STRING COMMENT 'Column.',
  mbr_deceased_date DATE COMMENT 'Column.',
  mbr_email STRING COMMENT 'Column.',
  mbr_phone_nbr STRING COMMENT 'Column.',
  mbr_mobile_nbr STRING COMMENT 'Column.',
  mbr_work_nbr STRING COMMENT 'Column.',
  mbr_sub_group_cd STRING COMMENT 'Column.',
  mbr_idcard_issue_date DATE COMMENT 'Column.',
  mbr_line_of_business STRING COMMENT 'Column.',
  mbr_text_opt_in STRING COMMENT 'Column.',
  mbr_current_riders STRING COMMENT 'Column.',
  mbr_authorized_rep STRING COMMENT 'Column.',
  mbr_alt_sub_nbr STRING COMMENT 'Column.',
  mbr_relationship_type STRING COMMENT 'Column.',
  mbr_salary_tier STRING COMMENT 'Column.',
  mbr_pcp_auto_assigned STRING COMMENT 'Column.',
  mbr_secured_flag STRING COMMENT 'Column.',
  mbr_pharmacy_discount_flag STRING COMMENT 'Column.',
  mbr_employee_id STRING COMMENT 'Column.',
  mbr_line_of_business_name STRING COMMENT 'Column.',
  mbr_responsible_party_id STRING COMMENT 'Column.',
  mbr_responsible_party_name STRING COMMENT 'Column.',
  mbr_deceased_flag STRING COMMENT 'Column.',
  mbr_pcp_lock_in_indicator STRING COMMENT 'Column.',
  mbr_alt_person_nbr STRING COMMENT 'Column.',
  mbr_state STRING COMMENT 'Column.',
  mbr_zip_code STRING COMMENT 'Column.',
  mbr_pcp_lock_in_type STRING COMMENT 'Column.',
  mbr_provider_group_name STRING COMMENT 'Column.',
  mbr_name_suffix STRING COMMENT 'Column.',
  mbr_sub_flag INT COMMENT 'Column.',
  mbr_sub_ssn STRING COMMENT 'Column.',
  mbr_extract_date DATE COMMENT 'Column.',
  mbr_medicaid_case_nbr STRING COMMENT 'Column.',
  mbr_relationship_ind STRING COMMENT 'Column.',
  source_system_code STRING COMMENT 'Column.',
  source_system_name STRING COMMENT 'Column.',
  record_hash STRING COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  valid_to_date TIMESTAMP COMMENT 'Column.',
  valid_from_date TIMESTAMP COMMENT 'Column.',
  CONSTRAINT pk_dim_member_history_v2 PRIMARY KEY (mbr_history_sk)
)
COMMENT 'Member history dimension table.';

-- COMMAND ----------

-- DBTITLE 1,Create fact_claim_header_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.fact_claim_header_v2 (
  clm_header_sk BIGINT NOT NULL COMMENT 'Primary key.',
  clm_id INT COMMENT 'Column.',
  clm_claim_id STRING COMMENT 'Claim business identifier referenced by fact_claim_detail_v2.clm_dtl_claim_id.',
  clm_original_source_claim_id STRING COMMENT 'Column.',
  clm_original_batch_nbr STRING COMMENT 'Column.',
  clm_patient_control_nbr STRING COMMENT 'Column.',
  clm_document_adj_control_nbr STRING COMMENT 'Column.',
  clm_claim_type STRING COMMENT 'Column.',
  clm_bill_type STRING COMMENT 'Column.',
  clm_authorization_nbr STRING COMMENT 'Column.',
  clm_ext_authorization_nbr STRING COMMENT 'Column.',
  clm_admit_date DATE COMMENT 'Column.',
  clm_claim_thru_date DATE COMMENT 'Column.',
  clm_discharge_date DATE COMMENT 'Column.',
  clm_admission_hour INT COMMENT 'Column.',
  clm_discharge_hour INT COMMENT 'Column.',
  clm_admission_type STRING COMMENT 'Column.',
  clm_admission_source STRING COMMENT 'Column.',
  clm_member_nbr STRING COMMENT 'Column.',
  clm_member_name STRING COMMENT 'Column.',
  clm_member_sk BIGINT COMMENT 'References dim_member_v2.member_sk.',
  clm_member_group_nbr STRING COMMENT 'Column.',
  clm_member_subgroup_nbr STRING COMMENT 'Column.',
  clm_plan_code STRING COMMENT 'Column.',
  clm_line_of_business STRING COMMENT 'Column.',
  clm_birth_weight DECIMAL(9,2) COMMENT 'Column.',
  clm_covered_days INT COMMENT 'Column.',
  clm_accident_st STRING COMMENT 'Column.',
  clm_attending_physician STRING COMMENT 'Column.',
  clm_attending_physician_spec STRING COMMENT 'Column.',
  clm_operating_provider_name STRING COMMENT 'Column.',
  clm_operating_provider_npi STRING COMMENT 'Column.',
  clm_submitting_provider STRING COMMENT 'Column.',
  clm_submitting_provider_spec STRING COMMENT 'Column.',
  clm_submitting_provider_type STRING COMMENT 'Column.',
  clm_billing_provider STRING COMMENT 'Column.',
  clm_referring_provider STRING COMMENT 'Column.',
  clm_referring_provider_spec STRING COMMENT 'Column.',
  clm_referring_provider_type STRING COMMENT 'Column.',
  clm_is_par_submitting_provider STRING COMMENT 'Column.',
  clm_is_par_referring_provider BOOLEAN COMMENT 'Column.',
  clm_is_par_rendering_provider BOOLEAN COMMENT 'Column.',
  clm_assigned_pcp STRING COMMENT 'Column.',
  clm_assigned_provider_site STRING COMMENT 'Column.',
  clm_insurance_id STRING COMMENT 'Column.',
  clm_member_contract_id STRING COMMENT 'Column.',
  clm_pcp_visit_flag INT COMMENT 'Column.',
  clm_pcp_in_type STRING COMMENT 'Column.',
  clm_pcp_wthld_pct DECIMAL(9,4) COMMENT 'Column.',
  clm_service_fac_npi STRING COMMENT 'Column.',
  clm_service_fac_loc_name STRING COMMENT 'Column.',
  clm_service_facility_address_sk BIGINT COMMENT 'References dim_address_v2.address_key.',
  clm_providers_account_no STRING COMMENT 'Column.',
  clm_onset_of_illness_date STRING COMMENT 'Column.',
  clm_admitting_diagnosis_code STRING COMMENT 'Column.',
  clm_admitting_diagnosis_method STRING COMMENT 'Column.',
  clm_diagnosis_1 STRING COMMENT 'Column.',
  clm_diagnosis_1_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_2 STRING COMMENT 'Column.',
  clm_diagnosis_2_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_3 STRING COMMENT 'Column.',
  clm_diagnosis_3_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_4 STRING COMMENT 'Column.',
  clm_diagnosis_4_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_5 STRING COMMENT 'Column.',
  clm_diagnosis_5_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_6 STRING COMMENT 'Column.',
  clm_diagnosis_6_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_7 STRING COMMENT 'Column.',
  clm_diagnosis_7_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_8 STRING COMMENT 'Column.',
  clm_diagnosis_8_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_9 STRING COMMENT 'Column.',
  clm_diagnosis_9_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_10 STRING COMMENT 'Column.',
  clm_diagnosis_10_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_11 STRING COMMENT 'Column.',
  clm_diagnosis_11_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_12 STRING COMMENT 'Column.',
  clm_diagnosis_12_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_13 STRING COMMENT 'Column.',
  clm_diagnosis_13_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_14 STRING COMMENT 'Column.',
  clm_diagnosis_14_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_15 STRING COMMENT 'Column.',
  clm_diagnosis_15_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_16 STRING COMMENT 'Column.',
  clm_diagnosis_16_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_17 STRING COMMENT 'Column.',
  clm_diagnosis_17_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_18 STRING COMMENT 'Column.',
  clm_diagnosis_18_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_19 STRING COMMENT 'Column.',
  clm_diagnosis_19_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_20 STRING COMMENT 'Column.',
  clm_diagnosis_20_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_21 STRING COMMENT 'Column.',
  clm_diagnosis_21_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_22 STRING COMMENT 'Column.',
  clm_diagnosis_22_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_23 STRING COMMENT 'Column.',
  clm_diagnosis_23_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_24 STRING COMMENT 'Column.',
  clm_diagnosis_24_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_25 STRING COMMENT 'Column.',
  clm_diagnosis_25_icd_method STRING COMMENT 'Column.',
  clm_diagnosis_1_poa STRING COMMENT 'Column.',
  clm_diagnosis_2_poa STRING COMMENT 'Column.',
  clm_diagnosis_3_poa STRING COMMENT 'Column.',
  clm_diagnosis_4_poa STRING COMMENT 'Column.',
  clm_diagnosis_5_poa STRING COMMENT 'Column.',
  clm_diagnosis_6_poa STRING COMMENT 'Column.',
  clm_diagnosis_7_poa STRING COMMENT 'Column.',
  clm_diagnosis_8_poa STRING COMMENT 'Column.',
  clm_diagnosis_9_poa STRING COMMENT 'Column.',
  clm_diagnosis_10_poa STRING COMMENT 'Column.',
  clm_diagnosis_11_poa STRING COMMENT 'Column.',
  clm_diagnosis_12_poa STRING COMMENT 'Column.',
  clm_diagnosis_13_poa STRING COMMENT 'Column.',
  clm_diagnosis_14_poa STRING COMMENT 'Column.',
  clm_diagnosis_15_poa STRING COMMENT 'Column.',
  clm_diagnosis_16_poa STRING COMMENT 'Column.',
  clm_diagnosis_17_poa STRING COMMENT 'Column.',
  clm_diagnosis_18_poa STRING COMMENT 'Column.',
  clm_diagnosis_19_poa STRING COMMENT 'Column.',
  clm_diagnosis_20_poa STRING COMMENT 'Column.',
  clm_diagnosis_21_poa STRING COMMENT 'Column.',
  clm_diagnosis_22_poa STRING COMMENT 'Column.',
  clm_diagnosis_23_poa STRING COMMENT 'Column.',
  clm_diagnosis_24_poa STRING COMMENT 'Column.',
  clm_diagnosis_25_poa STRING COMMENT 'Column.',
  clm_surgical_1 STRING COMMENT 'Column.',
  clm_surgical_icd_method_1 STRING COMMENT 'Column.',
  clm_surgical_2 STRING COMMENT 'Column.',
  clm_surgical_icd_method_2 STRING COMMENT 'Column.',
  clm_surgical_3 STRING COMMENT 'Column.',
  clm_surgical_icd_method_3 STRING COMMENT 'Column.',
  clm_surgical_4 STRING COMMENT 'Column.',
  clm_surgical_icd_method_4 STRING COMMENT 'Column.',
  clm_surgical_5 STRING COMMENT 'Column.',
  clm_surgical_icd_method_5 STRING COMMENT 'Column.',
  clm_surgical_6 STRING COMMENT 'Column.',
  clm_surgical_icd_method_6 STRING COMMENT 'Column.',
  clm_drg_code STRING COMMENT 'Column.',
  clm_service_type_code STRING COMMENT 'Column.',
  clm_cob_type STRING COMMENT 'Column.',
  clm_claim_timely_filing STRING COMMENT 'Column.',
  clm_accept_assignment_indicator STRING COMMENT 'Column.',
  clm_add_date DATE COMMENT 'Column.',
  clm_add_user STRING COMMENT 'Column.',
  clm_update_date DATE COMMENT 'Column.',
  clm_update_user STRING COMMENT 'Column.',
  clm_extract_date TIMESTAMP COMMENT 'Column.',
  clm_last_updated_date DATE COMMENT 'Column.',
  clm_original_insert_date DATE COMMENT 'Column.',
  clm_user_id STRING COMMENT 'Column.',
  clm_orig_source STRING COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  end_date TIMESTAMP COMMENT 'Column.',
  record_hash STRING COMMENT 'Column.',
  last_updated_date DATE COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  source_system_code STRING COMMENT 'Column.',
  source_system_name STRING COMMENT 'Column.',
  CONSTRAINT pk_fact_claim_header_v2 PRIMARY KEY (clm_header_sk)
)
COMMENT 'Claim header fact table.';

-- COMMAND ----------

-- DBTITLE 1,Create fact_claim_detail_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.fact_claim_detail_v2 (
  clm_dtl_claim_id STRING NOT NULL COMMENT 'References fact_claim_header_v2.clm_claim_id.',
  clm_dtl_line_nbr STRING NOT NULL COMMENT 'Primary key component.',
  clm_dtl_original_source_claim_id STRING COMMENT 'Column.',
  clm_dtl_source_system STRING COMMENT 'Column.',
  clm_dtl_member_nbr_sk STRING COMMENT 'Column.',
  clmdetail_admit_dt TIMESTAMP COMMENT 'Column.',
  clm_dtl_specific_dos_date DATE COMMENT 'Column.',
  clm_dtl_specific_dos_thru_date DATE COMMENT 'Column.',
  clm_dtl_apl_posting_date DATE COMMENT 'Column.',
  clm_dtl_claim_receive_date TIMESTAMP COMMENT 'Column.',
  clm_dtl_check_date TIMESTAMP COMMENT 'Column.',
  clm_dtl_last_update_date TIMESTAMP COMMENT 'Column.',
  clm_dtl_benefit_category STRING COMMENT 'Column.',
  clm_dtl_benefit_level STRING COMMENT 'Column.',
  clm_dtl_claim_type STRING COMMENT 'Column.',
  clm_dtl_allowed_amt DECIMAL(28,4) COMMENT 'Column.',
  clm_dtl_billed_amt DECIMAL(27,4) COMMENT 'Column.',
  clm_dtl_deduct_amt DECIMAL(27,4) COMMENT 'Column.',
  clm_dtl_net_amt DECIMAL(28,4) COMMENT 'Column.',
  clm_dtl_paid_amt DECIMAL(28,4) COMMENT 'Column.',
  clm_dtl_actual_paid_amt DECIMAL(38,4) COMMENT 'Column.',
  clm_dtl_not_covered_amt DECIMAL(27,4) COMMENT 'Column.',
  clm_dtl_co_insurance_amt DECIMAL(27,4) COMMENT 'Column.',
  clm_dtl_other_adjustments_amt DECIMAL(30,2) COMMENT 'Column.',
  clm_dtl_cob_savings DECIMAL(32,4) COMMENT 'Column.',
  clm_dtl_oic_paid_amt DECIMAL(19,4) COMMENT 'Column.',
  clm_dtl_oic_allowed_amt DECIMAL(19,4) COMMENT 'Column.',
  clm_dtl_interest_amt DECIMAL(38,6) COMMENT 'Column.',
  clm_dtl_prompt_pay_discount_amt DECIMAL(20,4) COMMENT 'Column.',
  clm_dtl_interest_discount_amt DECIMAL(38,6) COMMENT 'Column.',
  clm_dtl_interest_discount_flag STRING COMMENT 'Column.',
  clm_dtl_copay_amt DECIMAL(27,4) COMMENT 'Column.',
  clm_dtl_copay_reason STRING COMMENT 'Column.',
  clm_dtl_sc_cd STRING COMMENT 'Column.',
  clm_dtl_reason_code_sk STRING COMMENT 'Column.',
  clm_dtl_line_status STRING COMMENT 'Column.',
  clm_dtl_clean_claim_ind STRING COMMENT 'Column.',
  clm_dtl_place_of_service STRING COMMENT 'Column.',
  clm_dtl_fee_schedule_code STRING COMMENT 'Column.',
  clm_dtl_authorization_nbr STRING COMMENT 'Column.',
  clm_dtl_check_nbr STRING COMMENT 'Column.',
  clm_dtl_check_added_line_flag STRING COMMENT 'Column.',
  clm_dtl_check_message STRING COMMENT 'Column.',
  clm_dtl_submitting_provider STRING COMMENT 'Column.',
  clm_dtl_rendering_provider STRING COMMENT 'Column.',
  clm_dtl_rendering_provider_type STRING COMMENT 'Column.',
  clm_dtl_rendering_provider_spec STRING COMMENT 'Column.',
  clm_dtl_participating_provider STRING COMMENT 'Column.',
  clm_dtl_adjudication_status STRING COMMENT 'Column.',
  clm_dtl_procedure_code STRING COMMENT 'Column.',
  clm_dtl_procedure_modifier STRING COMMENT 'Column.',
  clm_dtl_modifier_2 STRING COMMENT 'Column.',
  clm_dtl_modifier_3 STRING COMMENT 'Column.',
  clm_dtl_modifier_4 STRING COMMENT 'Column.',
  clm_dtl_procedure_adj STRING COMMENT 'Column.',
  clm_dtl_procedure_qty DECIMAL(15,3) COMMENT 'Column.',
  clm_dtl_revenue_code STRING COMMENT 'Column.',
  clm_dtl_diagnosis_ind_1 STRING COMMENT 'Column.',
  clm_dtl_diagnosis_ind_2 STRING COMMENT 'Column.',
  clm_dtl_diagnosis_ind_3 STRING COMMENT 'Column.',
  clm_dtl_diagnosis_ind_4 STRING COMMENT 'Column.',
  clm_dtl_paid_days DECIMAL(36,3) COMMENT 'Column.',
  clm_dtl_anesthesia_time_units DECIMAL(12,2) COMMENT 'Column.',
  clm_dtl_cob_rule STRING COMMENT 'Column.',
  clm_dtl_wrap_network STRING COMMENT 'Column.',
  clm_dtl_returned_ntwrk_repric STRING COMMENT 'Column.',
  clm_dtl_user_id STRING COMMENT 'Column.',
  clm_dtl_extract_date TIMESTAMP COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  updated_at TIMESTAMP COMMENT 'Column.',
  created_at TIMESTAMP COMMENT 'Column.',
  CONSTRAINT pk_fact_claim_detail_v2 PRIMARY KEY (clm_dtl_claim_id, clm_dtl_line_nbr)
)
COMMENT 'Claim detail fact table.';

-- COMMAND ----------

-- DBTITLE 1,Create fact_member_enrollment_v2
CREATE OR REPLACE TABLE aw_serverless_stable_catalog.aibi_member_claims.fact_member_enrollment_v2 (
  source_system STRING COMMENT 'Column.',
  src_member_business_id INT COMMENT 'Column.',
  mbr_enr_source_member_id STRING COMMENT 'Column.',
  mbr_enr_insured_id STRING COMMENT 'Column.',
  mbr_enr_contract_id STRING COMMENT 'Column.',
  mbr_enr_insured_code STRING COMMENT 'Column.',
  mbr_enr_insured_add_date TIMESTAMP COMMENT 'Column.',
  mbr_enr_insured_event_date TIMESTAMP COMMENT 'Column.',
  mbr_enr_insured_event_id STRING COMMENT 'Column.',
  mbr_enr_insured_event_code STRING COMMENT 'Column.',
  mbr_enr_status STRING COMMENT 'Column.',
  mbr_enr_insured_event_add_date TIMESTAMP COMMENT 'Column.',
  mbr_enr_plan_id STRING COMMENT 'Column.',
  mbr_enr_line_of_business STRING COMMENT 'Column.',
  mbr_enr_line_of_business_id STRING COMMENT 'Column.',
  mbr_enr_group_name STRING COMMENT 'Column.',
  mbr_enr_subgroup_name STRING COMMENT 'Column.',
  mbr_enr_effective_date DATE COMMENT 'Column.',
  mbr_enr_termination_date DATE COMMENT 'Column.',
  mbr_enr_termination_event_date DATE COMMENT 'Column.',
  mbr_enr_termination_reason STRING COMMENT 'Column.',
  mbr_enr_product_id STRING COMMENT 'Column.',
  mbr_enr_group_ck STRING COMMENT 'Column.',
  mbr_enr_group_code STRING COMMENT 'Column.',
  mbr_enr_subgroup_ck STRING COMMENT 'Column.',
  mbr_enr_subgroup_code STRING COMMENT 'Column.',
  is_active BOOLEAN COMMENT 'Column.',
  id_value STRING COMMENT 'Column.',
  id_type STRING COMMENT 'Column.',
  member_sk BIGINT COMMENT 'References dim_member_v2.member_sk.',
  enrollment_sk STRING NOT NULL COMMENT 'Primary key.',
  payload_hash STRING COMMENT 'Column.',
  CONSTRAINT pk_fact_member_enrollment_v2 PRIMARY KEY (enrollment_sk)
)
COMMENT 'Member enrollment fact table.';
